var fullName = 'moamle hashim';
var isCool = true;
var totalPets = 1;
var unknown = null;
var never;
console.log('value of full name:', fullName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('value of unknown:', unknown);
console.log('value of never:', never);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
console.log('typeof unknown:', typeof unknown);
console.log('typeof never:', typeof never);
